# Generated by Django 4.2.19 on 2025-02-26 09:18

from django.db import migrations, models
import my_restaurant.models


class Migration(migrations.Migration):

    dependencies = [
        ('my_restaurant', '0006_table_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Special',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('image', models.ImageField(default=my_restaurant.models.default_image, upload_to='specials/')),
            ],
        ),
    ]
