# Generated by Django 4.2.19 on 2025-02-26 20:59

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_restaurant', '0008_alter_restaurant_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='image',
            field=models.CharField(default='default.jpg', max_length=2083),
        ),
    ]
